### ISSUE TITLE
Delete saves does not work with saves made via console

### ISSUE THREAD

**Issue by Kukoro** [erri120/ctd-on-death#1]
If I save my game via "save <name>" the script fails to delete the saves.

new Regex($@"^Save\d+_({id})+[^.]+.(ess|skse)$");
new Regex($@"^Autosave\d+_({id})+[^.]+.(ess|skse)$");
new Regex($@"^Quicksave\d+_({id})+[^.]+.(ess|skse)$");

Regex does not account for names without Save, Autosave or Quicksave in name.

**Comment by erri120** [comment]
The only way to also delete named saves is by parsing the save file. This has problems since you can only compare by the player character name so if you use the default name for multiple characters, it will end up deleting more saves.

**Comment by erri120** [comment]
Added in cdd77e03d0996160bf6289aeeb8bff720c8bfe3c
